### ISSUE TITLE
afiliados.json publica información privada de ~1300 personas.

### ISSUE THREAD

**Issue by santisiri** [PartidoDeLaRed/afiliaciones#18]
La app está corriendo en github? Porque afiliados.json muestra la info de todos los afiliados y no esta necesariamente bueno que esa información esté públicamente accesible.

Muy buen laburo la app en sí!

**Comment by mjlescano** [comment]
@santisiri Gracias por avisar! Ahi lo estoy borrando del history, se me escapó en alguna prueba.

**Comment by santisiri** [comment]
Buenisimo! Glad to help.
