### ISSUE TITLE
Agregar estado para saber si se checkeó si está afiliado a otro partido

### ISSUE THREAD

**Issue by mjlescano** [PartidoDeLaRed/afiliaciones#2]

**Comment by fvilledary** [comment]
Resuelto con commit [https://github.com/PartidoDeLaRed/afiliaciones/commit/408cd4540a865f808689d0cce3f8c5353cb2d68a](https://github.com/PartidoDeLaRed/afiliaciones/commit/408cd4540a865f808689d0cce3f8c5353cb2d68a)
