### ISSUE TITLE
Agregar Nombres Completos de Padre y Madre

### ISSUE THREAD

**Issue by mjlescano** [PartidoDeLaRed/afiliaciones#3]

**Comment by fvilledary** [comment]
closed with commit [https://github.com/PartidoDeLaRed/afiliaciones/commit/34d011b943b37ad18009afad5dee9435c9f4b44e](https://github.com/PartidoDeLaRed/afiliaciones/commit/34d011b943b37ad18009afad5dee9435c9f4b44e)
