### ISSUE TITLE
Checkbox para que se pueda marcar si el peer quiere ayudar a las afiliaciones

### ISSUE THREAD

**Issue by mjlescano** [PartidoDeLaRed/afiliaciones#4]
"[x] Quiero Ayudar a conseguir más afiliados"

**Comment by fvilledary** [comment]
closed with commit [https://github.com/PartidoDeLaRed/afiliaciones/commit/34d011b943b37ad18009afad5dee9435c9f4b44e](https://github.com/PartidoDeLaRed/afiliaciones/commit/34d011b943b37ad18009afad5dee9435c9f4b44e)
