### ISSUE TITLE
Agregar opción para elegir forma de contacto para completar la ficha

### ISSUE THREAD

**Issue by mjlescano** [PartidoDeLaRed/afiliaciones#5]
Opciones:
- Quiero que me contacten para terminar las fichas
- Me acerco a un punto de afiliacion

**Comment by fvilledary** [comment]
closed with commit [https://github.com/PartidoDeLaRed/afiliaciones/commit/34d011b943b37ad18009afad5dee9435c9f4b44e](https://github.com/PartidoDeLaRed/afiliaciones/commit/34d011b943b37ad18009afad5dee9435c9f4b44e)
