### ISSUE TITLE
Opcion para guardar el estado de las fichas

### ISSUE THREAD

**Issue by mjlescano** [PartidoDeLaRed/afiliaciones#7]
Hacer falta saber si las fichas están listas para ser entregadas, y marca si ya se entregaron y cúando.

**Comment by fvilledary** [comment]
Resuelto con commit [https://github.com/PartidoDeLaRed/afiliaciones/commit/408cd4540a865f808689d0cce3f8c5353cb2d68a](https://github.com/PartidoDeLaRed/afiliaciones/commit/408cd4540a865f808689d0cce3f8c5353cb2d68a)
