### ISSUE TITLE
Guardar en la DB quién agregó al peer

### ISSUE THREAD

**Issue by mjlescano** [PartidoDeLaRed/afiliaciones#8]
- [x] Hay que agregar un campo `user` en peer. Tiene el id del user/admin.
- [ ] Mostrarlo, pero que no se pueda editar

**Comment by fvilledary** [comment]
Ya guarda quien lo creó o lo editó por última vez. Commit [https://github.com/PartidoDeLaRed/afiliaciones/commit/7979c509ed2a8e13dc93a744c19ff92c94df1ea2](https://github.com/PartidoDeLaRed/afiliaciones/commit/7979c509ed2a8e13dc93a744c19ff92c94df1ea2)
